"""Generate a config from the open timeline.

Hand-listing sixteen tracks, their files and their clip gains is the dullest and
most error-prone part of setting up a new show, and every one of those values is
already sitting in the timeline.  So read them out instead of asking for them.
"""
from __future__ import annotations
import os

PROGRAM_HINTS = ("track", "program", "backing", "playback", "band", "orch")

# Room mics do not get gated - they are the sound of the room, and closing them
# between lines would pump the ambience. Left out of the mic list, but reported,
# so nothing is silently dropped either.
ROOM_HINTS = ("condenser", "audience", "room", "ambient", "overhead",
              "crowd", "house", "boundary", "pzm")


def match_tracks(tl, audio_dir: str, log=None):
    """(mic rows, program file) for the open timeline.

    A track counts only if its first clip's filename actually exists in the audio
    directory - the analysis reads those files directly, so a name that does not
    resolve would fail later and more confusingly.
    """
    rows, program, room = [], None, []
    for tn in range(1, int(tl.GetTrackCount("audio")) + 1):
        items = tl.GetItemListInTrack("audio", tn) or []
        if not items:
            continue
        clip = items[0].GetName()
        name = tl.GetTrackName("audio", tn) or f"A{tn}"
        if not os.path.exists(os.path.join(audio_dir, clip)):
            if log:
                log(f"  skipping A{tn} {name}: {clip} is not in the audio directory")
            continue
        label = (name + " " + clip).lower()
        if program is None and any(h in label for h in PROGRAM_HINTS):
            program = clip                       # masks the musical numbers
            continue
        if any(h in label for h in ROOM_HINTS):
            room.append((tn, name, clip))
            continue
        rows.append((tn, name, clip))
    return rows, program, room


def render(rows, program, audio_dir: str, duration: float,
           gains: dict | None = None, midi_out: str = "loopMIDI Port",
           midi_in: str = "loopMIDI Port B", room=()) -> str:
    """The TOML text.  Kept separate from Resolve so it can be tested."""
    if not rows:
        raise ValueError("no audio tracks matched files in the audio directory")
    first = rows[0][0]
    numbers = [tn for tn, _, _ in rows]
    lines = ["# Generated by `micrider init`.",
             "# Check `window` before writing anything - it defaults to the whole",
             "# timeline, and automation is normally written one act at a time.",
             "",
             "[audio]",
             f'dir     = "{audio_dir.replace(os.sep, "/")}"']
    if program:
        lines.append(f'program = "{program}"      # backing tracks; masks the numbers')
    else:
        lines.append('# program = "Tracks.wav"   # a backing-track file here masks the numbers')
    lines += ['offset  = "auto"           # read from the clips themselves',
              f"window  = [0.0, {duration:.1f}]",
              "",
              "[timeline]"]
    if numbers == list(range(first, first + len(numbers))):
        lines.append(f"first_track = {first}")
        lines.append("tracks = [")
        for tn, name, clip in rows:
            lines.append(f'  "{clip}",'.ljust(30) + f"# A{tn}  {name}")
        lines.append("]")
    else:                                        # gaps: address tracks explicitly
        lines.append("[timeline.map]")
        for tn, name, clip in rows:
            lines.append(f'{tn} = "{clip}"'.ljust(30) + f"# {name}")
    if room:
        lines += ["", "# Left out as room mics - add them above if that is wrong."]
        lines += [f'# "{c}"'.ljust(30) + f"# A{tn}  {n}" for tn, n, c in room]
    lines += ["", "[midi]", f'out = "{midi_out}"', f'in  = "{midi_in}"']
    if gains:
        wanted = [c for _, _, c in rows] + ([program] if program else [])
        present = [c for c in wanted if c in gains]
        if present:
            lines += ["", "# Clip gain already applied in the timeline.", "[gains]"]
            lines += [f'"{c}" = {gains[c]}' for c in present]
    return "\n".join(lines) + "\n"
